#!/usr/bin/env bash
#This script resolves localhost to 127.0.0.2 and facebook.com to 8.8.8.8
if [ "$EUID" -ne 0 ]; then
	echo "please run as root or with sudo"
	exit
fi
cat <<EOL >> /etc/hosts
127.0.0.2	localhost
8.8.8.8		facebook.com
EOL
